TO - DO - Task
Please complete all the problem listed below.
4.1 Exercise on Functions:
Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [24]:
#2330784
#Pramdip Shrestha
# unit measurement
def convert_length(value, conversion_type):
    """So to convert between meters and feet based on the conversion type."""
    if conversion_type == "m_to_ft":
        return value * 3.28084
    elif conversion_type == "ft_to_m":
        return value / 3.28084
    else:
        raise ValueError("Unsupported length conversion type")

def convert_weight(value, conversion_type):
    """So to convert between kilograms and pounds based on the conversion type."""
    if conversion_type == "kg_to_lbs":
        return value * 2.20462  # kilograms to pounds
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462  # pounds to kilograms
    else:
        raise ValueError("Unsupported weight conversion type")

def convert_volume(value, conversion_type):
    """So to convert between liters and gallons based on the conversion type."""
    if conversion_type == "L_to_gal":
        return value * 0.264172  # liters to gallons
    elif conversion_type == "gal_to_L":
        return value / 0.264172  # gallons to liters
    else:
        raise ValueError("Unsupported volume conversion type")

def main():
    """Main function that handles user input and performs the selected conversion."""
    print("Welcome to the Unit Converter!")

    # Prompt user to choose the type of conversion
    print("Choose the type of conversion:")
    print("1. Length (m/ft)")
    print("2. Weight (kg/lbs)")
    print("3. Volume (L/gal)")

    try:
        conversion_type = int(input("Enter the number for the type of conversion (1/2/3): "))
        if conversion_type not in [1, 2, 3]:
            raise ValueError("Invalid choice. Please enter 1, 2, or 3.")

        # To prompt user for the value to convert
        value = float(input("Enter the value to be converted: "))

        #To Perform the selected conversion
        if conversion_type == 1:
            print("Choose the conversion type:")
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            sub_choice = int(input("Enter 1 or 2: "))
            if sub_choice == 1:
                result = convert_length(value, "m_to_ft")
                print(f"{value} meters is equal to {result:.2f} feet.")
            elif sub_choice == 2:
                result = convert_length(value, "ft_to_m")
                print(f"{value} feet is equal to {result:.2f} meters.")
            else:
                print("Invalid choice.")

        elif conversion_type == 2:
            print("Choose the conversion type:")
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            sub_choice = int(input("Enter 1 or 2: "))
            if sub_choice == 1:
                result = convert_weight(value, "kg_to_lbs")
                print(f"{value} kilograms is equal to {result:.2f} pounds.")
            elif sub_choice == 2:
                result = convert_weight(value, "lbs_to_kg")
                print(f"{value} pounds is equal to {result:.2f} kilograms.")
            else:
                print("Invalid choice.")

        elif conversion_type == 3:
            print("Choose the conversion type:")
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            sub_choice = int(input("Enter 1 or 2: "))
            if sub_choice == 1:
                result = convert_volume(value, "L_to_gal")
                print(f"{value} liters is equal to {result:.2f} gallons.")
            elif sub_choice == 2:
                result = convert_volume(value, "gal_to_L")
                print(f"{value} gallons is equal to {result:.2f} liters.")
            else:
                print("Invalid choice.")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()


Welcome to the Unit Converter!
Choose the type of conversion:
1. Length (m/ft)
2. Weight (kg/lbs)
3. Volume (L/gal)
Enter the number for the type of conversion (1/2/3): 2
Enter the value to be converted: 3
Choose the conversion type:
1. Kilograms to Pounds
2. Pounds to Kilograms
Enter 1 or 2: 2
3.0 pounds is equal to 1.36 kilograms.


Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

18

6CS012 Worksheet - 0 Siman Giri

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [25]:
#2330784
#Pramdip Shrestha

def calculate_sum(numbers):
    """So it returns the sum of the numbers in the list."""
    return sum(numbers)

def calculate_average(numbers):
    """So it returns the average of the numbers in the list."""
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """Returns the maximum value from the list of numbers."""
    return max(numbers)

def find_minimum(numbers):
    """Returns the minimum value from the list of numbers."""
    return min(numbers)

def main():
    """Main function to handle user input and perform selected mathematical operations."""
    print("Welcome to the Mathematical Operations Program!")

    try:
        #To prompt the user to input a list of numbers
        numbers_input = input("Enter a list of numbers separated by spaces: ")
        numbers = [float(num) for num in numbers_input.split()]

        # To ensure the list is not empty
        if not numbers:
            raise ValueError("The list of numbers cannot be empty.")

        # To prompt the user to choose an operation
        print("\nChoose an operation:")
        print("1. Find the sum of the numbers")
        print("2. Find the average of the numbers")
        print("3. Find the maximum number")
        print("4. Find the minimum number")

        operation_choice = int(input("Enter the number for the operation (1/2/3/4): "))

        if operation_choice == 1:
            result = calculate_sum(numbers)
            print(f"The sum of the numbers is: {result}")
        elif operation_choice == 2:
            result = calculate_average(numbers)
            print(f"The average of the numbers is: {result}")
        elif operation_choice == 3:
            result = find_maximum(numbers)
            print(f"The maximum number is: {result}")
        elif operation_choice == 4:
            result = find_minimum(numbers)
            print(f"The minimum number is: {result}")
        else:
            print("Invalid choice. Please choose a valid operation.")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()


Welcome to the Mathematical Operations Program!
Enter a list of numbers separated by spaces: 5

Choose an operation:
1. Find the sum of the numbers
2. Find the average of the numbers
3. Find the maximum number
4. Find the minimum number
Enter the number for the operation (1/2/3/4): 3
The maximum number is: 5.0


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [28]:
#2330784
#Pramdip Shrestha
def extract_every_other(lst):
    """Returns a new list containing every other element from the original list."""
    return lst[::2]


input_list = [1, 2, 3, 4, 5, 6]
output_list = extract_every_other(input_list)
print("Extracted every other element:", output_list)


Extracted every other element: [1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [27]:
#2330784
#Pramdip Shrestha
def get_sublist(lst, start, end):
    """Returns a sublist from the list starting at index 'start' and ending at index 'end' (inclusive)."""
    return lst[start:end+1]


input_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
output_sublist = get_sublist(input_list, start_index, end_index)
print("Sublist:", output_sublist)


Sublist: [3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [29]:
#2330784
#Pramdip Shrestha
def reverse_list(lst):
    """Returns a reversed version of the list using slicing."""
    return lst[::-1]


input_list = [1, 2, 3, 4, 5]
reversed_list = reverse_list(input_list)
print("Reversed list:", reversed_list)


Reversed list: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [30]:
#2330784
#Pramdip Shrestha
def remove_first_last(lst):
    """Returns a sublist without the first and last elements using slicing."""
    return lst[1:-1]


input_list = [1, 2, 3, 4, 5]
resulting_sublist = remove_first_last(input_list)
print("Sublist without the first and last elements:", resulting_sublist)


Sublist without the first and last elements: [2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [31]:
#2330784
#Pramdip Shrestha
def get_first_n(lst, n):
    """Returns the first n elements of the list using slicing."""
    return lst[:n]


input_list = [1, 2, 3, 4, 5]
n = 3
first_n_elements = get_first_n(input_list, n)
print("First n elements:", first_n_elements)


First n elements: [1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [32]:
#2330784
#Pramdip Shrestha
def get_last_n(lst, n):
    """So it returns the last n elements of the list using slicing."""
    return lst[-n:]


input_list = [1, 2, 3, 4, 5]
n = 2
last_n_elements = get_last_n(input_list, n)
print("Last n elements:", last_n_elements)


Last n elements: [4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [33]:
#2330784
#Pramdip Shrestha
def reverse_skip(lst):
    """Returns a new list containing every second element starting from the second-to-last, moving backward."""
    return lst[-2::-2]


input_list = [1, 2, 3, 4, 5, 6]
reversed_skipped_elements = reverse_skip(input_list)
print("Reversed and skipped elements:", reversed_skipped_elements)


Reversed and skipped elements: [5, 3, 1]


4.3 Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [34]:
#2330784
#Pramdip Shrestha
def flatten(lst):
    flat_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            flat_list.extend(flatten(sublist))  # Recursively flatten sublists
        else:
            flat_list.append(sublist)
    return flat_list


nested_list = [[1, 2], [3, 4], [5]]
flattened_list = flatten(nested_list)
print(flattened_list)


[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [35]:
#2330784
#Pramdip Shrestha
def access_nested_element(lst, indices):
    element = lst  # Start with the full list
    for index in indices:
        element = element[index]  # Access the next level
    return element


lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(lst, indices)
print(result)


6


3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [36]:
#2330784
#Pramdip Shrestha
def sum_nested(lst):
    total = 0
    for element in lst:
        if isinstance(element, list):
            total += sum_nested(element)  # Recursively sum sublists
        else:
            total += element  # To add numbers directly
    return total


nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(result)


21


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [37]:
#2330784
#Pramdip Shrestha
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            new_sublist = remove_element(item, elem)
            if new_sublist:
                result.append(new_sublist)
        elif item != elem:
            result.append(item)
    return result

lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
modified_list = remove_element(lst, elem)
print(modified_list)


[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [38]:
#2330784
#Pramdip Shrestha
def find_max(lst):
    max_value = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))
        else:
            max_value = max(max_value, item)
    return max_value

nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print(result)


6


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [39]:
#2330784
#Pramdip Shrestha
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
result = count_occurrences(lst, elem)
print(result)


3


7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [40]:
#2330784
#Pramdip Shrestha
def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print(result)


[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [41]:
#2330784
#Pramdip Shrestha
def average_nested(lst):
    def helper(lst):
        total, count = 0, 0
        for item in lst:
            if isinstance(item, list):
                sub_total, sub_count = helper(item)
                total += sub_total
                count += sub_count
            else:
                total += item
                count += 1
        return total, count

    total, count = helper(lst)
    return total / count if count > 0 else 0

nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print(result)


3.5


10 To - Do - NumPy
Please complete all the problems listed below:
10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [42]:
#2330784
#Pramdip Shrestha
import numpy as np

# Task 1: To Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))

# Task 2: To Initialize an all one array with size 4x2
ones_array = np.ones((4, 2))

# Task 3: To Return a new array of given shape and type, filled with fill value
filled_array = np.full((3, 3), 7)  # Example shape (3, 3) and fill value 7

# Task 4: To Return a new array of zeros with same shape and type as a given array
existing_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(existing_array)

# Task 5: to Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(existing_array)

# Task 6: For an existing list new_list = [1, 2, 3, 4], convert to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)

empty_array, ones_array, filled_array, zeros_like_array, ones_like_array, numpy_array


(array([[1.00000000e+00, 0.00000000e+00],
        [1.77635684e-15, 1.00000000e+00]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]),
 array([[0, 0],
        [0, 0]]),
 array([[1, 1],
        [1, 1]]),
 array([1, 2, 3, 4]))

Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [43]:
#2330784
#Pramdip Shrestha
# Task 1:To Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)

# Task 2:To Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)

# Task 3:To Create a 3x3 identity matrix
identity_matrix = np.eye(3)

# Task 4:To Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_of_array = random_array.mean()

# Task 5:To Create a 10x10 array with random values and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()

# Task 6:To Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Replace 5th element (index 4) with 1

# Task 7:To Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]

# Task 8:To Create a 2d array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0

# Task 9:To Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

array_10_to_49, matrix_3x3, identity_matrix, mean_of_array, min_value, max_value, zero_array, reversed_arr, border_array, checkerboard


(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 0.4408455941506183,
 0.007969330437126443,
 0.9983248935851906,
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0, 4, 0, 0, 2, 1]),
 array([[1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]]))

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [22]:
#2330784
#Pramdip Shrestha
# Arrays as per the problem
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1: Add the two arrays
array_sum = x + y

# Task 2: Subtract the two arrays
array_diff = x - y

# Task 3: Multiply the array with an integer (e.g., multiply by 2)
array_mult = x * 2

# Task 4: Find the square of each element of the array
array_square = np.square(x)

# Task 5: Find the dot product between:
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

# Task 6: Concatenate x and y along row and concatenate v and w along column
concat_x_y_row = np.concatenate((x, y), axis=0)
concat_v_w_column = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

# Task 7: Concatenate x and v; error explanation
try:
    concat_x_v = np.concatenate((x, v), axis=1)
except Exception as e:
    concat_x_v_error = str(e)

array_sum, array_diff, array_mult, array_square, dot_v_w, dot_x_v, dot_x_y, concat_x_y_row, concat_v_w_column, concat_x_v_error


(array([[ 6,  8],
        [10, 13]]),
 array([[-4, -4],
        [-4, -3]]),
 array([[ 2,  4],
        [ 6, 10]]),
 array([[ 1,  4],
        [ 9, 25]]),
 219,
 array([29, 77]),
 array([[19, 22],
        [50, 58]]),
 array([[1, 2],
        [3, 5],
        [5, 6],
        [7, 8]]),
 array([[ 9, 11],
        [10, 12]]),
 'all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)')

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [44]:
#2330784
#Pramdip Shrestha
# Arrays A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Task 1: Prove A * A^(-1) = I (Identity Matrix)
A_inv = np.linalg.inv(A)  # Inverse of A
identity_matrix = np.dot(A, A_inv)  # A * A_inv

# Task 2: Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)

# Task 3: Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))

# Solving the system of linear equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9
# Matrix form: AX = B

# A matrix represents the coefficients
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
# B matrix represents the right-hand side
B_matrix = np.array([-1, -3, 9])

# Solving for X (x, y, z)
X = np.linalg.solve(A_matrix, B_matrix)

# Solve using np.linalg.inv
X_inv_method = np.dot(np.linalg.inv(A_matrix), B_matrix)

identity_matrix, AB, BA, AB_T, BT_AT, X, X_inv_method


(array([[1.00000000e+00, 0.00000000e+00],
        [1.77635684e-15, 1.00000000e+00]]),
 array([[23, 13],
        [51, 29]]),
 array([[36, 44],
        [13, 16]]),
 array([[23, 51],
        [13, 29]]),
 array([[23, 51],
        [13, 29]]),
 array([ 2.,  1., -2.]),
 array([ 2.,  1., -2.]))